module.exports = {
  mailReq: "EmailId are Required!",
  mailInvalid: "Invalid Email Format",
  mailLength: "EmailId length should be between 8 and 40 characters",
  fnRequire: "FirstName are Required!",
  fnLength: "FirstName length should be between 3 and 11 characters",
  lnRequire: "LastName are Required!",
  lnLength: "LastName length should be between 3 and 11 characters",
  passRequire: "Password are Required!",
  passLength: "Password length should be between 3 and 11 characters",
  dobRequire: "DoB are Required!",
  dobLength: "DoB length should be between 9 and 12 characters",
  phoneRequire: "PhoneNum are Required!",
  phoneLength: "PhoneNum length should be between 10 and 14 characters",
  mailExist: "This User Already Registered. Change MailID",
  passWorng: "Incorrect Password",
  mailWrong: "Incorrect EmailId",
  notUpdate: "Not Update Your Details...",
  noToke: "No Token Present",
  tokenWrong: "Token Invalid!",
  add: "User Register Successfully",
  log: "Login Successfully",
  verify: "Your Details Is..",
  update: "Profile Updated Successfully",
  delete: "Your Details is Deleted",
};
